apiVersion: v1
kind: Pod
metadata:
  name: justin-nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: NGINX_DB_ENV
        valueFrom:
          configMapKeyRef:
            name: justin-env
            key: DB_URL
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
